* HEP Toolkit
A collection of scripts and tools to make life a little easier.
** Lab Notebook
lab-notebook.el is a collection of functions that will parse an org
file and produce a structured set of org files that can be exported
to a website.  

DOCUMENT ME
** Panda Parse
panda_parse is a python script that will open your panda jobs page
and print two files panda_retrieve.txt for datasets that had less
than 5% failure rate and panda_resubmit.txt for datasets that should
be resubmitted. If a dataset needs to be resubmitted, the output
datset name is printed to stdout.  

Everything is hard coded right now.  If I have time some day I might
make it more user friendly.
*** Requirements
- Beautiful Soup 4
- urllib
- python 2.7+
** purge_cern_inbox
This is a working example of how to parse imap requests in
python... Its very specific, but could be tailored to do more
sophisticated things (like manage Panda jobs from a chron job and
resubmit until 100% success rate)

** split-tree
This does what it says, takes an input tree and splits it in two.
Right now its hard coded for trees called "micro" and it only splits
them in two parts, but all the boilerplate is there, its a small
exercise to add command line options for the tree and to put it in a
loop to split it into n parts.  

Just type make in the repo where you checked this out, make sure root
is activated as the Makefile depends on root-config being in your
path. 
